### ISSUE TITLE
Substitute does not working

### ISSUE THREAD

**Issue by deemytch** [processone/fast_yaml#20]
erlang/OTP24
elixir 1.12
archlinux
fast_yaml  1.0.31

substitutes like that won't decoded.
```
defaults:
  coreAPI: &coreAPI
    coreAPI: [publish, disable]

ctrl:
  document:
    <<: *coreAPI
    other: [values]
```
Instead of 
`{ :ok, %{ ctrl: %{ document: %{ coreAPI: ["publish","disable"], other: ["values"] }...`

I get 
`{ :ok, [%{ ctrl: %{ document: %{ "<<": "coreAPI", other: ["values"] }...`

At the same time ruby version YAML decoding that fine.
